Repository kiwicom/orbit-swiftui, pull requests merged in 2022-12, with the labels that each got.

#380 Disable autolabeler
  .github/release-drafter.yml
Labels: automation

#379 Update BarButton and NavigationButton
  Snapshots/iPad/BarButtonTests/testBarButton.1.png
  Snapshots/iPad/NavigationButtonTests/testNavigationButtonBack.1.png
  Snapshots/iPad/NavigationButtonTests/testNavigationButtonClose.1.png
  Snapshots/iPhone/BarButtonTests/testBarButton.1.png
  Snapshots/iPhone/NavigationButtonTests/testNavigationButtonBack.1.png
  Snapshots/iPhone/NavigationButtonTests/testNavigationButtonClose.1.png
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/BarButton.swift
  Sources/Orbit/Support/Components/NavigateButton.swift
  Sources/Orbit/Support/Components/NavigationButton.swift
  Tests/SnapshotTests/Assertions.swift
  Tests/SnapshotTests/SnapshotTestCase.swift
  Tests/SnapshotTests/Support Components/BarButtonTests.swift
  Tests/SnapshotTests/Support Components/ListItemTests.swift
  Tests/SnapshotTests/Support Components/NavigationButtonTests.swift
  Tests/SnapshotTests/Support Components/ScreenLayoutModifierTests.swift
  Tests/SnapshotTests/Support Components/TagGroupTests.swift
  Tests/SnapshotTests/Support Components/TextConcatenationTests.swift
Labels: enhancement

#381 Allow ButtonLink style in Card
  Sources/Orbit/Components/Card.swift
Labels: enhancement

#388 Update default BarButton Icon size, make it configurable
  Snapshots/iPad/BarButtonTests/testBarButton.1.png
  Snapshots/iPad/NavigationButtonTests/testNavigationButtonBack.1.png
  Snapshots/iPad/NavigationButtonTests/testNavigationButtonClose.1.png
  Snapshots/iPhone/BarButtonTests/testBarButton.1.png
  Snapshots/iPhone/NavigationButtonTests/testNavigationButtonBack.1.png
  Snapshots/iPhone/NavigationButtonTests/testNavigationButtonClose.1.png
  Sources/Orbit/Support/Components/BarButton.swift
Labels: enhancement

#389 Show ButtonLink Tile disclosure for fully custom content
  Sources/Orbit/Components/Tile.swift
Labels: bug

#391 Automatically update snapshots in relevant branches
  .github/workflows/ci.yml
  .github/workflows/regenerate_snapshots.yml
Labels: automation

#398 Add `Collapse` component
  Snapshots/iPad/CollapseTests/testCollapse.1.png
  Snapshots/iPhone/CollapseTests/testCollapse.1.png
  Sources/Orbit/Components/Collapse.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Support/Previews/PreviewProvider+Extensions.swift
  Sources/OrbitStorybook/ContentPlaceholder.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCollapse.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
  Sources/OrbitStorybook/Storybook+Items.swift
  Tests/SnapshotTests/Components/CollapseTests.swift
Labels: feature

#402 Replace `isEnabled` property with `isEnabled` environment key
  Snapshots/iPad/InputFieldTests/testInputFieldsPassword.1.png
  Snapshots/iPhone/InputFieldTests/testInputFieldsPassword.1.png
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Support/Components/SecureTextField.swift
  Sources/Orbit/Support/Components/TagGroup.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Forms/InputState.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCheckbox.swift
  Sources/OrbitStorybook/Detail/Items/StorybookInputField.swift
  Sources/OrbitStorybook/Detail/Items/StorybookListChoice.swift
  Sources/OrbitStorybook/Detail/Items/StorybookRadio.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSelect.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSwitch.swift
Labels: maintenance

#409 Unify `InputField` sizing and fix `SecureTextField` size
  Snapshots/iPad/InputFieldTests/testInputFields.2.png
  Snapshots/iPad/NotificationBadgeTests/testNotificationBadges.1.png
  Snapshots/iPad/TabsTests/testTabs.1.png
  Snapshots/iPad/TabsTests/testTabs.2.png
  Snapshots/iPhone/InputFieldTests/testInputFields.2.png
  Snapshots/iPhone/NotificationBadgeTests/testNotificationBadges.1.png
  Snapshots/iPhone/TabsTests/testTabs.1.png
  Snapshots/iPhone/TabsTests/testTabs.2.png
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/NotificationBadge.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Components/SecureTextField.swift
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Previews/Measurements.swift
  Sources/Orbit/Support/Previews/PreviewFormatting.swift
  Tests/SnapshotTests/Components/InputFieldTests.swift
  Tests/SnapshotTests/Components/TabsTests.swift
Labels: bug
