Repository kiwicom/orbit-swiftui, pull requests merged in 2022-01, with the labels that each got.

#4 Add basic action to build the package
  .github/workflows/swift.yml
Labels: automation

#5 ListChoice component
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/ListChoiceGroup.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Support/Views/Header.swift
Labels: enhancement

#7 Add tokens-updater workflow
  .github/tokens-updater.sh
  .github/workflows/tokens-updater.yml
Labels: automation

#11 Update List and ListItem components to support TextLinks.
  Sources/Orbit/Components/List.swift
  Sources/Orbit/Components/ListItem.swift
Labels: feature

#12 Remove legacy Orbit illustrations.
  Sources/Orbit/Foundation/Illustrations/Illustrations.swift
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/BookingSuccess.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/BookingSuccess.imageset/thankyou.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/BookingSuccess.imageset/thankyou@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/BookingSuccess.imageset/thankyou@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ForceUpdate.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ForceUpdate.imageset/force-update-ipad.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ForceUpdate.imageset/force-update-ipad@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ForceUpdate.imageset/force-update-iphone.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ForceUpdate.imageset/force-update-iphone@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ForceUpdate.imageset/force-update-iphone@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Notifications.imageset/App_notification.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Notifications.imageset/App_notification@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Notifications.imageset/App_notification@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Notifications.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ThrowAwayTicket.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ThrowAwayTicket.imageset/tat-banner.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ThrowAwayTicket.imageset/tat-banner@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/ThrowAwayTicket.imageset/tat-banner@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Transport.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Transport.imageset/Transport.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Transport.imageset/Transport@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/Transport.imageset/Transport@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/selectTravelers.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/selectTravelers.imageset/LP_Invite1.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/selectTravelers.imageset/LP_Invite2.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Orbit TODO/selectTravelers.imageset/LP_Invite3.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/PlaceholderDestinationCrop.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/PlaceholderDestinationCrop.imageset/place_placehold.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/PlaceholderDestinationCropIPad.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/PlaceholderDestinationCropIPad.imageset/place_ipad_placehold.png
Labels: maintenance

#14 Fix/tile listchoice updates
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Error404.imageset/Error404.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Improve.imageset/Improve.png
Labels: maintenance
