Repository kiwicom/orbit-swiftui, pull requests merged in 2022-08, with the labels that each got.

#261 Icon script should sanitise dots in names
  Automation/update_icons.py
Labels: automation, maintenance

#266 Experimental darkmode updates
  Automation/update_colors.py
  Snapshots/iOS15_iPad_(9th_generation)/ToastTests/testToasts.1.png
  Snapshots/iOS15_iPhone_13/ToastTests/testToasts.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ToastTests/testToasts.1.png
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Foundation/Colors/Colors.xcassets/Cloud/Cloud Dark.colorset/Contents.json
  Sources/Orbit/Foundation/Colors/Colors.xcassets/Cloud/Cloud Darker Active.colorset/Contents.json
  Sources/Orbit/Foundation/Colors/Colors.xcassets/Cloud/Cloud Darker Hover.colorset/Contents.json
  Sources/Orbit/Foundation/Colors/Colors.xcassets/Cloud/Cloud Darker.colorset/Contents.json
  Sources/Orbit/Foundation/Colors/Colors.xcassets/Product/Product Darker.colorset/Contents.json
  Sources/Orbit/Support/Images/Images.xcassets/Navigation/NavigateBack.imageset/Contents.json
  Sources/Orbit/Support/Images/Images.xcassets/Navigation/NavigateClose.imageset/Contents.json
  Sources/Orbit/Support/Storybook/Storybook.swift
  Sources/Orbit/Support/Storybook/StorybookDetail.swift
Labels: enhancement, automation

#271 Update DocC generation to use Xcode 14
  .github/workflows/publish-docc.yml
Labels: automation

#272 Add ScreenLayoutPaddingKey
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Support/Environment Keys/IsInsideScreenLayoutKey.swift
  Sources/Orbit/Support/Environment Keys/ScreenLayoutPaddingKey.swift
  Sources/Orbit/Support/Layout/IgnoreScreenLayoutHorizontalPaddingModifier.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
Labels: enhancement

#280 Generate documentation comments for country codes with full country names
  .github/workflows/update-country-flags.yml
  Automation/update_country_flags.py
  Sources/Orbit/Foundation/CountryFlags/CountryFlags.swift
Labels: automation

#277 Update Elevation modifier
  .github/workflows/regenerate_snapshots.yml
  Snapshots/iOS15_iPad_(9th_generation)/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iOS15_iPad_(9th_generation)/DialogTests/testDialog.1.png
  Snapshots/iOS15_iPad_(9th_generation)/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iOS15_iPad_(9th_generation)/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TileTests/testTiles.1.png
  Snapshots/iOS15_iPad_(9th_generation)/ToastTests/testToasts.1.png
  Snapshots/iOS15_iPhone_13/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iOS15_iPhone_13/DialogTests/testDialog.1.png
  Snapshots/iOS15_iPhone_13/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iOS15_iPhone_13/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPhone_13/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_13/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPhone_13/TileTests/testTiles.1.png
  Snapshots/iOS15_iPhone_13/ToastTests/testToasts.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/DialogTests/testDialog.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TileTests/testTiles.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ToastTests/testToasts.1.png
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Foundation/Elevations/Elevation.swift
  Sources/Orbit/Orbit.docc/Foundation/Elevation.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/TileBorder.swift
Labels: bug, automation, maintenance

#279 Add check if all components have snapshot tests
  .github/workflows/ci.yml
  Automation/check_components_have_snapshot_tests.sh
  Snapshots/iOS15_iPad_(9th_generation)/ButtonLinkTests/testButtonLinks.1.png
  Snapshots/iOS15_iPhone_13/ButtonLinkTests/testButtonLinks.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ButtonLinkTests/testButtonLinks.1.png
  Tests/SnapshotTests/Components/AlertTests.swift
  Tests/SnapshotTests/Components/BadgeListTests.swift
  Tests/SnapshotTests/Components/BadgeTests.swift
  Tests/SnapshotTests/Components/ButtonLinkTests.swift
  Tests/SnapshotTests/Components/ButtonTests.swift
  Tests/SnapshotTests/Components/CardTests.swift
  Tests/SnapshotTests/Components/CarrierLogoTests.swift
  Tests/SnapshotTests/Components/CheckboxTests.swift
  Tests/SnapshotTests/Components/ChoiceTileTests.swift
  Tests/SnapshotTests/Components/CountryFlagTests.swift
  Tests/SnapshotTests/Components/DialogTests.swift
  Tests/SnapshotTests/Components/EmptyStateTests.swift
  Tests/SnapshotTests/Components/HeadingTests.swift
  Tests/SnapshotTests/Components/HorizontalScrollTests.swift
  Tests/SnapshotTests/Components/IconTests.swift
  Tests/SnapshotTests/Components/IllustrationTests.swift
  Tests/SnapshotTests/Components/InputFieldTests.swift
  Tests/SnapshotTests/Components/KeyValueTests.swift
  Tests/SnapshotTests/Components/ListChoiceTests.swift
  Tests/SnapshotTests/Components/ListTests.swift
  Tests/SnapshotTests/Components/NotificationBadgeTests.swift
  Tests/SnapshotTests/Components/RadioTests.swift
  Tests/SnapshotTests/Components/SelectTests.swift
  Tests/SnapshotTests/Components/SeparatorTests.swift
  Tests/SnapshotTests/Components/SkeletonTests.swift
  Tests/SnapshotTests/Components/SocialButtonTests.swift
  Tests/SnapshotTests/Components/SwitchTests.swift
  Tests/SnapshotTests/Components/TabsTests.swift
  Tests/SnapshotTests/Components/TagTests.swift
  Tests/SnapshotTests/Components/TextLinkTests.swift
  Tests/SnapshotTests/Components/TextTests.swift
  Tests/SnapshotTests/Components/TileGroupTests.swift
  Tests/SnapshotTests/Components/TileTests.swift
  Tests/SnapshotTests/Components/TimelineTests.swift
  Tests/SnapshotTests/Components/ToastTests.swift
Labels: automation

#282 Fix screenLayout-related documentation
  Sources/Orbit/Orbit.docc/Foundation/ScreenLayout.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Layout/IgnoreScreenLayoutHorizontalPaddingModifier.swift
Labels: bug, documentation, maintenance

#281 Make `PreviewWrapper` internal
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Previews/PreviewWrapper.swift
  Sources/Orbit/Support/Previews/StateWrapper.swift
Labels: documentation, maintenance

#278 Add `Heading` and `Icon` concatenation support
  Snapshots/iOS15_iPad_(9th_generation)/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iOS15_iPhone_13/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TextConcatenationTests/testTextConcatenation.1.png
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Foundation/Typography/OrbitFont.swift
  Sources/Orbit/Support/TextConcatenation/ConcatenatedText.swift
  Sources/Orbit/Support/TextConcatenation/TextRepresentable+Concatenation.swift
  Sources/Orbit/Support/TextConcatenation/TextRepresentable.swift
  Tests/SnapshotTests/TextConcatenationTests.swift
Labels: feature

#273 Remove fixed size of EmptyState button
  Snapshots/iOS15_iPad_(9th_generation)/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPhone_13/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TileGroupTests/testTileGroups.1.png
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/HorizontalScroll.swift
  Sources/Orbit/Components/Illustration.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Components/Timeline.swift
  Sources/Orbit/Support/Components/Label.swift
  Sources/Orbit/Support/Environment Keys/IdealSizeKey.swift
  Sources/Orbit/Support/Forms/FormFieldWrapper.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Forms/KeyValueField.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
  Sources/Orbit/Support/Previews/PreviewProvider+Extensions.swift
Labels: bug, enhancement

#288 Support TextLinks in FormField wrapper
  Sources/Orbit/Support/Forms/FormFieldLabel.swift
  Sources/Orbit/Support/Forms/FormFieldWrapper.swift
Labels: enhancement

#292 Use TextLink-enabled FormFieldLabel in InputField and Select
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Support/Forms/FormFieldLabel.swift
  Sources/Orbit/Support/Forms/FormFieldWrapper.swift
Labels: enhancement, feature

#287 Allow customizing colors
  Automation/update_colors.py
  Sources/Orbit/Foundation/Colors/Colors.swift
  Sources/Orbit/Foundation/Colors/Gradients.swift
  Sources/Orbit/Foundation/Colors/UIColors.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookColors.swift
Labels: enhancement, automation

#294 Add basic `TextRepresentable` support to `Text`
  Snapshots/iOS15_iPad_(9th_generation)/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iOS15_iPhone_13/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TextConcatenationTests/testTextConcatenation.1.png
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/TextConcatenation/ConcatenatedText.swift
  Sources/Orbit/Support/TextConcatenation/TextRepresentable+Concatenation.swift
  Sources/Orbit/Support/TextConcatenation/TextRepresentable.swift
Labels: enhancement, feature

#296 Release fixes
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Switch.swift
Labels: feature, maintenance
