Repository kiwicom/orbit-swiftui, pull requests merged in 2022-07, with the labels that each got.

#221 BadgeList support for ref styling
  Sources/Orbit/Components/BadgeList.swift
Labels: enhancement

#229 Reduce compression resistance for SecureTextFied to fit wrapper
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Components/SecureTextField.swift
Labels: bug, feature

#226 Allow multiline content in Badge
  Snapshots/iOS15_iPad_(9th_generation)/BadgeTests/testBadges.1.png
  Snapshots/iOS15_iPhone_13/BadgeTests/testBadges.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/BadgeTests/testBadges.1.png
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Tile.swift
Labels: feature

#234 Add ViewBuilder to TimelineStep init
  Snapshots/iOS15_iPad_(9th_generation)/TimelineTests/testTimeline.1.png
  Snapshots/iOS15_iPhone_13/TimelineTests/testTimeline.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TimelineTests/testTimeline.1.png
  Sources/Orbit/Components/Timeline.swift
  Sources/Orbit/Foundation/Typography/Font.swift
  Sources/Orbit/Support/Components/TimelineStep.swift
  Sources/Orbit/Support/Components/TimelineStepContent.swift
Labels: feature

#240 Update Github actions by splitting them into separate update tasks.
  .github/update-colors.sh
  .github/update-icons.sh
  .github/update-illustrations.sh
  .github/workflows/regenerate_snapshots.yml
  .github/workflows/update-colors.yml
  .github/workflows/update-country-flags.yml
  .github/workflows/update-icons.yml
  .github/workflows/update-illustrations.yml
  Automation/regenerate_snapshots.sh
Labels: automation

#247 Fix height reader
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Forms/FormFieldWrapper.swift
  Sources/Orbit/Support/Layout/ContentHeightReader.swift
Labels: bug

#246 Split updater labels
  .github/workflows/update-colors.yml
  .github/workflows/update-icons.yml
  .github/workflows/update-illustrations.yml
  Automation/update_icons.py
Labels: automation

#248 Make `Dialog` content alignment configurable
  Snapshots/iOS15_iPad_(9th_generation)/DialogTests/testDialog.1.png
  Snapshots/iOS15_iPhone_13/DialogTests/testDialog.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/DialogTests/testDialog.1.png
  Sources/Orbit/Components/Dialog.swift
Labels: enhancement, feature

#253 Update README.md
  README.md
Labels: documentation, maintenance
