Repository kiwicom/orbit-swiftui, pull requests merged in 2022-11, with the labels that each got.

#356 Make `AccessibilityID` reusable and extensible by client
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/KeyValue.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Accessibility/AccessibilityID.swift
  Sources/Orbit/Support/Components/PasswordStrengthIndicator.swift
  Sources/Orbit/Support/Forms/FieldLabel.swift
  Sources/Orbit/Support/Forms/FieldMessage.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
Labels: accessibility

#346 Update timeline design
  Snapshots/iPad/TimelineTests/testTimeline.1.png
  Snapshots/iPad/TimelineTests/testTimelineItem.1.png
  Snapshots/iPhone/TimelineTests/testTimeline.1.png
  Snapshots/iPhone/TimelineTests/testTimelineItem.1.png
  Sources/Orbit/Components/Timeline.swift
  Sources/Orbit/Orbit.docc/Components/Extensions/Timeline.md
  Sources/Orbit/Support/Components/TimelineIndicator.swift
  Sources/Orbit/Support/Components/TimelineItem.swift
  Sources/Orbit/Support/Components/TimelineLine.swift
  Sources/Orbit/Support/Components/TimelineStep.swift
  Sources/Orbit/Support/Components/TimelineStepContent.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTimeline.swift
  Tests/SnapshotTests/Components/TimelineTests.swift
Labels: documentation, feature, maintenance

#357 Allow specifying horizontal size classes for `ignoreScreenLayoutHorizontalPadding`
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Support/Layout/IgnoreScreenLayoutHorizontalPaddingModifier.swift
Labels: feature

#367 Fix the text concatenation runtime warning
  Sources/Orbit/Components/Icon.swift
Labels: bug

#376 Add missing illustrations
  Sources/Orbit/Foundation/Illustrations/Illustrations.swift
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/FareLockSuccess.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/FareLockSuccess.imageset/FareLockSuccess@1x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/FareLockSuccess.imageset/FareLockSuccess@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/FareLockSuccess.imageset/FareLockSuccess@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/MusicalInstruments.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/MusicalInstruments.imageset/MusicalInstruments@1x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/MusicalInstruments.imageset/MusicalInstruments@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/MusicalInstruments.imageset/MusicalInstruments@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Pets.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Pets.imageset/Pets@1x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Pets.imageset/Pets@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/Pets.imageset/Pets@3x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/SportsEquipment.imageset/Contents.json
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/SportsEquipment.imageset/SportsEquipment@1x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/SportsEquipment.imageset/SportsEquipment@2x.png
  Sources/Orbit/Foundation/Illustrations/Illustrations.xcassets/SportsEquipment.imageset/SportsEquipment@3x.png
Labels: enhancement, maintenance
