Repository kiwicom/orbit-swiftui, pull requests merged in 2022-03, with the labels that each got.

#43 Fix ListItem
  Sources/Orbit/Components/ListItem.swift
Labels: bug

#47 Added bundle colors for use in UIKit.
  Sources/Orbit/Foundation/Colors/Gradients.swift
Labels: maintenance

#44 `CarrierLogo` component
  Sources/Orbit/Components/CarrierLogo.swift
Labels: feature

#56 Update `ListChoice` height to 48.
  Sources/Orbit/Components/ListChoice.swift
Labels: feature

#60 Replace ListChoiceGroup with Card
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/ListChoiceGroup.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Support/Views/TileBorder.swift
Labels: maintenance

#59 Rename Heading to Label and unify spacing
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Views/Label.swift
Labels: maintenance

#61 Update Text and Heading sizes
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Views/Label.swift
Labels: enhancement

#62 Update icon sizes
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/CarrierLogo.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/ListItem.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TimelineStep.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Views/BarButton.swift
  Sources/Orbit/Support/Views/Label.swift
Labels: enhancement, feature, maintenance

#66 Simplify Card content padding and spacing
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/TileGroup.swift
Labels: feature

#67 Fixes for upcoming 0.8.14
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/List.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/ListItem.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Views/Label.swift
Labels: bug, maintenance

#46 Implement Secured InputField component
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Views/SecureTextField.swift
Labels: feature
