Repository kiwicom/orbit-swiftui, pull requests merged in 2022-06, with the labels that each got.

#153 Release updates
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/NotificationBadge.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Components/BarButton.swift
  Sources/Orbit/Support/Components/Label.swift
  Sources/Orbit/Support/Components/PasswordStrengthIndicator.swift
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Components/TimelineStep.swift
  Sources/Orbit/Support/Forms/FormFieldMessage.swift
  Sources/Orbit/Support/Forms/FormFieldWrapper.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookIcons.swift
  Sources/Orbit/Support/Storybook/Storybook+Items.swift
Labels: feature, maintenance

#157 Only update DocC when a release is published
  .github/workflows/publish-docc.yml
Labels: automation

#158 Add basic DocC catalog with data from README
  .github/release-drafter.yml
  Sources/Orbit/Orbit.docc/FileStructureAndNaming.md
  Sources/Orbit/Orbit.docc/GettingStarted.md
  Sources/Orbit/Orbit.docc/Orbit.md
  Sources/Orbit/Orbit.docc/Resources/storybook.png
  Sources/Orbit/Orbit.docc/Resources/usage.png
Labels: documentation, automation, maintenance

#161 Remove padding from Separator and support Dynamic Type
  Sources/Orbit/Components/Separator.swift
Labels: enhancement, accessibility

#162 Release updates
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ListChoice.swift
Labels: maintenance

#164 Release updates
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/KeyValue.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Accessibility/AccessibilityID.swift
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Components/TileBorder.swift
  Sources/Orbit/Support/Forms/FormFieldMessage.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Forms/KeyValueField.swift
  Sources/Orbit/Support/Layout/TextStrut.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookIcons.swift
Labels: maintenance, accessibility

#167 Update component accessibility
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/KeyValue.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Accessibility/AccessibilityID.swift
  Sources/Orbit/Support/Forms/KeyValueField.swift
Labels: enhancement, maintenance, accessibility

#171 Remove duplicate accessibility element for text plus textlinks
  Sources/Orbit/Components/Text.swift
Labels: bug, accessibility

#143 Support custom formatting in InputField
  Sources/Orbit/Components/InputField.swift
Labels: feature

#179 Hide input trailing button in disabled state
  Sources/Orbit/Components/InputField.swift
Labels: enhancement

#180 Update README.md
  Documentation/docc.png
  README.md
Labels: maintenance

#182 Update documentation structure
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/HorizontalScroll.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Orbit.docc/Components/Components.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Alert.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Card.md
  Sources/Orbit/Orbit.docc/Components/Extensions/HorizontalScroll.md
  Sources/Orbit/Orbit.docc/Components/Extensions/List.md
  Sources/Orbit/Orbit.docc/Components/Extensions/ListChoice.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Tabs.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Tag.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Tile.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Timeline.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Toast.md
  Sources/Orbit/Orbit.docc/Foundation.md
  Sources/Orbit/Orbit.docc/Orbit.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/Tab.swift
Labels: documentation, maintenance

#184 Remove "related components" from documentation comments
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/HorizontalScroll.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Illustration.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/KeyValue.swift
  Sources/Orbit/Components/List.swift
  Sources/Orbit/Components/NotificationBadge.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/TextLink.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Forms/KeyValueField.swift
Labels: documentation

#192 Fix storybook crashes on component selection
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookIcons.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookIllustrations.swift
  Sources/Orbit/Support/Storybook/Storybook+Items.swift
  Sources/Orbit/Support/Storybook/Storybook.swift
  Sources/Orbit/Support/Storybook/StorybookDetail.swift
Labels: bug, feature

#193 Add first Orbit tutorial
  01-01-hello_orbit-s08 2.png
  01-01-hello_orbit-s08.png
  Sources/Orbit/Orbit.docc/Orbit.md
  Sources/Orbit/Orbit.docc/Resources/Articles/storybook.png
  Sources/Orbit/Orbit.docc/Resources/Articles/usage.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s01.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s02.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s03.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s04.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s05.swift
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s06.swift
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s07.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s07.swift
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s07~dark.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s08.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s08.swift
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s08~dark.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-essentials@2x.png
  Sources/Orbit/Orbit.docc/Resources/Tutorials/rocket.png
  Sources/Orbit/Orbit.docc/Tutorials/01-01-hello_orbit.tutorial
  Sources/Orbit/Orbit.docc/Tutorials/Tutorials.tutorial
Labels: documentation

#188 Add elevation levels
  Snapshots/iOS15_iPad_(9th_generation)/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_13/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPhone_13/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TabsTests/testTabs.1.png
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Foundation/Elevations/Elevation.swift
  Sources/Orbit/Orbit.docc/Foundation/Elevation.md
  Sources/Orbit/Orbit.docc/Foundation/Foundation.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Environment Keys/IsElevationEnabledKey.swift
  Sources/Orbit/Support/Environment Keys/IsExpandedKey.swift
Labels: documentation, feature, maintenance

#197 Remove some unused images
  01-01-hello_orbit-s08 2.png
  01-01-hello_orbit-s08.png
  Documentation/storybook.png
  Documentation/usage.png
Labels: maintenance

#199 Improve prerendered shadows in `elevation`
  Snapshots/iOS15_iPad_(9th_generation)/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_13/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPhone_13/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/SwitchTests/testSwitches.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TabsTests/testTabs.1.png
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Foundation/Elevations/Elevation.swift
Labels: maintenance

#198 Add the `documentation` category to release drafter
  .github/release-drafter.yml
Labels: automation

#194 Restrict `NotificationBadge` to always be a circle
  Snapshots/iOS15_iPad_(9th_generation)/NotificationBadgeTests/testNotificationBadges.1.png
  Snapshots/iOS15_iPhone_13/NotificationBadgeTests/testNotificationBadges.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/NotificationBadgeTests/testNotificationBadges.1.png
  Sources/Orbit/Components/NotificationBadge.swift
Labels: feature

#211 Simplify Illustration API
  Sources/Orbit/Components/Illustration.swift
Labels: enhancement

#203 Remove clear button from InputField
  Snapshots/iOS15_iPad_(9th_generation)/InputFieldTests/testInputFields.1.png
  Snapshots/iOS15_iPhone_13/InputFieldTests/testInputFields.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/InputFieldTests/testInputFields.1.png
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Accessibility/AccessibilityID.swift
Labels: feature

#215 Support enum type for `CountryFlag`
  .github/workflows/flags-updater.yml
  Automation/update_country_flags.py
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Foundation/CountryFlags/CountryFlags.swift
Labels: automation, feature

#214 Create a screen layout modifier
  Snapshots/iOS15_iPad_(9th_generation)/CardTests/testCards.1.png
  Snapshots/iOS15_iPad_(9th_generation)/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iOS15_iPad_(9th_generation)/IllustrationTests/testIllustrations.1.png
  Snapshots/iOS15_iPad_(9th_generation)/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPad_(9th_generation)/TileTests/testTiles.1.png
  Snapshots/iOS15_iPhone_13/CardTests/testCards.1.png
  Snapshots/iOS15_iPhone_13/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iOS15_iPhone_13/IllustrationTests/testIllustrations.1.png
  Snapshots/iOS15_iPhone_13/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iOS15_iPhone_13/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_13/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPhone_13/TileTests/testTiles.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/CardTests/testCards.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/IllustrationTests/testIllustrations.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TabsTests/testTabs.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TileGroupTests/testTileGroups.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/TileTests/testTiles.1.png
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Illustration.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Skeleton.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Foundation/Borders/BorderRadius.swift
  Sources/Orbit/Orbit.docc/Foundation/Foundation.md
  Sources/Orbit/Orbit.docc/Foundation/ScreenLayout.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Components/TileBorder.swift
  Sources/Orbit/Support/Environment Keys/IsInsideScreenLayoutKey.swift
  Sources/Orbit/Support/Layout/ContainerWidth.swift
  Sources/Orbit/Support/Layout/Layout.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookColors.swift
  Sources/Orbit/Support/Storybook/Storybook+Items.swift
  Sources/Orbit/Support/Storybook/Storybook.swift
  Sources/Orbit/Support/Storybook/StorybookDetail.swift
  Tests/SnapshotTests/ScreenLayoutModifierTests.swift
Labels: documentation, feature, maintenance

#217 Add missing BadgeList variants.
  Snapshots/iOS15_iPad_(9th_generation)/BadgeListTests/testBadgeLists.1.png
  Snapshots/iOS15_iPhone_13/BadgeListTests/testBadgeLists.1.png
  Snapshots/iOS15_iPhone_SE_(1st_generation)/BadgeListTests/testBadgeLists.1.png
  Sources/Orbit/Components/BadgeList.swift
Labels: enhancement
