Repository kiwicom/orbit-swiftui, pull requests merged in 2022-02, with the labels that each got.

#15 Choice tile centered
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/ChoiceTile.swift
Labels: feature, maintenance

#17 Make Header more customizable.
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Views/Header.swift
Labels: feature

#18 Alert update
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Support/Views/Header.swift
Labels: feature

#19 Input field suffix
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Support/Forms/FormFieldMessage.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Layout/Strut.swift
Labels: feature

#20 ListChoiceGroupStyle
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/ListChoiceGroup.swift
Labels: feature

#21 Add `value` text view to `ListChoice`
  Sources/Orbit/Components/ListChoice.swift
Labels: feature

#23 Fix default Header color.
  Sources/Orbit/Support/Views/Header.swift
Labels: bug

#24 Fix formatted text font sizing.
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/TextLinks/TagAttributedStringBuilder.swift
Labels: bug, feature

#25 Added EmptyState component.
  Sources/Orbit/Components/EmptyState.swift
Labels: feature

#27 Fix choicetile status
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/ListItem.swift
  Sources/Orbit/Support/Views/TileBorder.swift
Labels: bug, feature

#28 Allow custom content in Alert.
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/EmptyState.swift
Labels: feature

#30 Fix iOS13 button tap area.
  Sources/Orbit/Components/Button.swift
Labels: bug, feature

#31 Fix custom content spacing for Alert.
  Sources/Orbit/Components/Alert.swift
Labels: bug, feature

#35 Add width option to adjust horizontal sizing for wrapper components.
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/ListChoiceGroup.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Support/Layout/ContainerWidth.swift
Labels: bug

#38 Add script to update icons automatically
  .github/tokens-updater.sh
  Automation/update_icons.py
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/HorizontalScroll.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Foundation/Icons/Icons.swift
  Sources/Orbit/Foundation/Icons/Icons.ttf
  Sources/Orbit/Support/Views/TagGroup.swift
Labels: automation, feature

#36 Replace Illustration sizing with single enum option.
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Illustration.swift
Labels: enhancement, maintenance

#42 Update Illustration layout options.
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Illustration.swift
  Sources/Orbit/Support/Layout/Layout.swift
Labels: enhancement, feature
