Repository kiwicom/orbit-swiftui, pull requests merged in 2022-05, with the labels that each got.

#115 Update README.md
  README.md
Labels: documentation, maintenance

#120 Basic text support for dynamic type
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Foundation/Typography/Font.swift
  Sources/Orbit/Support/Components/Label.swift
Labels: enhancement, feature, accessibility

#119 Create a unified wrapper for form fields
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Support/Forms/FormFieldWrapper.swift
Labels: bug, enhancement

#121 Icon baseline calculation for dynamic fonts
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Icon.swift
Labels: enhancement, accessibility

#124 Components should have minimal height not fixed
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/KeyValue.swift
  Sources/Orbit/Components/List.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Separator.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/TextLink.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/Timeline.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Foundation/Spacing/Spacing.swift
  Sources/Orbit/Foundation/Typography/Font.swift
  Sources/Orbit/Support/Components/SecureTextField.swift
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Components/TagGroup.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Layout/FrameWidthAtLeastHeightModifier.swift
  Sources/Orbit/Support/Layout/Strut.swift
  Sources/Orbit/Support/Layout/TextStrut.swift
Labels: bug, maintenance, accessibility

#116 Update README.md
  README.md
Labels: documentation

#125 Create NotificationBadge component
  Sources/Orbit/Components/NotificationBadge.swift
  Sources/Orbit/Support/Storybook/Storybook+Items.swift
  component-status.yaml
Labels: feature

#128 Support leading icon in Tag
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Support/Components/TagGroup.swift
Labels: enhancement

#132 Run the design token update once a week on Monday
  .github/workflows/tokens-updater.yml
Labels: automation

#133 Speed up `ToastQueue` typecheck
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Toast/ToastQueue.swift
Labels: maintenance

#135 Remove accessibility from TextStrut.
  Sources/Orbit/Support/Layout/TextStrut.swift
Labels: bug

#137 Use linkColor from ListItem style
  Sources/Orbit/Support/Components/ListItem.swift
Labels: bug

#136 Fix Select and InputField suffix touchability
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
Labels: bug

#138 Fix accessibility for TextStruct and Tag
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/Layout/TextStrut.swift
Labels: bug, feature, accessibility

#141 Support TextLink in BadgeList
  Sources/Orbit/Components/BadgeList.swift
Labels: enhancement

#81 PasswordStrengthIndicator
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Components/PasswordStrengthIndicator.swift
Labels: enhancement

#148 Update README.md
  README.md
Labels: documentation, maintenance

#144 Unify `Icon.Content` and `Icon.Symbol` enums usage
  Automation/update_colors.py
  Automation/update_icons.py
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/List.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/NotificationBadge.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Foundation/Colors/Colors.swift
  Sources/Orbit/Foundation/Colors/UIColors.swift
  Sources/Orbit/Foundation/Icons/Icon.Content+Extensions.swift
  Sources/Orbit/Foundation/Icons/Icons.swift
  Sources/Orbit/Support/Components/BarButton.swift
  Sources/Orbit/Support/Components/Label.swift
  Sources/Orbit/Support/Components/ListItem.swift
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Components/TagGroup.swift
  Sources/Orbit/Support/Components/TimelineStep.swift
  Sources/Orbit/Support/Forms/FormFieldMessage.swift
  Sources/Orbit/Support/Forms/LazyVStackIfAvailable.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookIcons.swift
  Sources/Orbit/Support/Storybook/Storybook+Items.swift
  Sources/Orbit/Support/Storybook/Storybook.swift
  Sources/Orbit/Support/Toast/ToastQueue.swift
Labels: automation, feature, maintenance
