Repository kiwicom/orbit-swiftui, pull requests merged in 2022-10, with the labels that each got.

#326 Set CI Xcode version to 13.4
  .github/workflows/ci.yml
  .github/workflows/regenerate_snapshots.yml
Labels: automation

#328 Update token update branch names to prevent collisions
  .github/workflows/update-colors.yml
  .github/workflows/update-icons.yml
  .github/workflows/update-illustrations.yml
Labels: automation

#348 Delete OrbitStatic and OrbitDynamic targets
  .github/workflows/ci.yml
  Package.swift
Labels: automation

#345 OrbitStorybook target
  .github/workflows/ci.yml
  Package.swift
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Orbit.docc/GettingStarted.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/TimelineStep.swift
  Sources/Orbit/Support/Layout/LazyVStack.swift
  Sources/Orbit/Support/Previews/PreviewWrapper.swift
  Sources/Orbit/Support/Storybook/Foundation/StorybookTypography.swift
  Sources/Orbit/Support/Storybook/StorybookDetail.swift
  Sources/Orbit/Support/StringExtensions.swift
  Sources/OrbitStorybook/ContentPlaceholder.swift
  Sources/OrbitStorybook/Detail/Items/StorybookAlert.swift
  Sources/OrbitStorybook/Detail/Items/StorybookBadge.swift
  Sources/OrbitStorybook/Detail/Items/StorybookBadgeList.swift
  Sources/OrbitStorybook/Detail/Items/StorybookButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookButtonLink.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCard.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCarrierLogo.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCheckbox.swift
  Sources/OrbitStorybook/Detail/Items/StorybookChoiceTile.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCountryFlag.swift
  Sources/OrbitStorybook/Detail/Items/StorybookDialog.swift
  Sources/OrbitStorybook/Detail/Items/StorybookEmptyState.swift
  Sources/OrbitStorybook/Detail/Items/StorybookHorizontalScroll.swift
  Sources/OrbitStorybook/Detail/Items/StorybookIcon.swift
  Sources/OrbitStorybook/Detail/Items/StorybookIllustration.swift
  Sources/OrbitStorybook/Detail/Items/StorybookInputField.swift
  Sources/OrbitStorybook/Detail/Items/StorybookKeyValue.swift
  Sources/OrbitStorybook/Detail/Items/StorybookList.swift
  Sources/OrbitStorybook/Detail/Items/StorybookListChoice.swift
  Sources/OrbitStorybook/Detail/Items/StorybookNotificationBadge.swift
  Sources/OrbitStorybook/Detail/Items/StorybookRadio.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSelect.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSeparator.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSkeleton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSocialButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSwitch.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTabs.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTag.swift
  Sources/OrbitStorybook/Detail/Items/StorybookText.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTextLink.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTile.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTileGroup.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTimeline.swift
  Sources/OrbitStorybook/Detail/Items/StorybookToast.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
  Sources/OrbitStorybook/Foundation/StorybookColors.swift
  Sources/OrbitStorybook/Foundation/StorybookIcons.swift
  Sources/OrbitStorybook/Foundation/StorybookIllustrations.swift
  Sources/OrbitStorybook/Foundation/StorybookTypography.swift
  Sources/OrbitStorybook/Storybook+Items.swift
  Sources/OrbitStorybook/Storybook.swift
  Sources/OrbitStorybook/TutorialScreen.swift
Labels: documentation, automation, feature, maintenance

#347 Check types are referenced in DocC
  .github/workflows/ci.yml
  Package.swift
  Plugins/CheckDocumentation/main.swift
  Sources/Orbit/Orbit.docc/Components/Components.md
  Sources/Orbit/Support/TextConcatenation/TextRepresentable.swift
Labels: documentation, automation, maintenance
