Repository kiwicom/orbit-swiftui, pull requests merged in 2023-08, with the labels that each got.

#642 Apply accessibility id to knob, not the whole track
  Sources/Orbit/Components/Slider.swift
Labels: bug, accessibility

#640 Update `ScreenLayoutModifier` alignment
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
Labels: maintenance

#651 Add focus modifier for inputfields
  Sources/Orbit/Support/Environment Keys/Identifier.swift
  Sources/Orbit/Support/Environment Keys/InputFieldFocusKey.swift
  Sources/Orbit/Support/TextFields/TextField.swift
Labels: feature

#654 Update focus state for `InputField`
  Snapshots/iPad/InputContentTests/testInputContent.1.png
  Snapshots/iPad/InputContentTests/testInputContent.2.png
  Snapshots/iPhone/InputContentTests/testInputContent.1.png
  Snapshots/iPhone/InputContentTests/testInputContent.2.png
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Forms/InputContentButtonStyle.swift
  Tests/SnapshotTests/Support Components/InputContentTests.swift
Labels: enhancement

#653 Update inline label design
  Snapshots/iPad/InputContentTests/testInputContent.1.png
  Snapshots/iPad/InputContentTests/testInputContent.2.png
  Snapshots/iPad/InputFieldTests/testInputFields.1.png
  Snapshots/iPad/SelectTests/testSelects.1.png
  Snapshots/iPhone/InputContentTests/testInputContent.1.png
  Snapshots/iPhone/InputContentTests/testInputContent.2.png
  Snapshots/iPhone/InputFieldTests/testInputFields.1.png
  Snapshots/iPhone/SelectTests/testSelects.1.png
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Forms/InputContentButtonStyle.swift
  Sources/Orbit/Support/Layout/IsEmpty.swift
  Sources/Orbit/Support/TextFields/TextField.swift
Labels: enhancement

#655 Concatenated Text should be sized the same as regular Text
  Snapshots/iPad/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iPad/TextConcatenationTests/testTextConcatenationSizing.1.png
  Snapshots/iPad/TextTests/testTexts.5.png
  Snapshots/iPad/TextTests/testTexts.6.png
  Snapshots/iPhone/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iPhone/TextConcatenationTests/testTextConcatenationSizing.1.png
  Snapshots/iPhone/TextTests/testTexts.5.png
  Snapshots/iPhone/TextTests/testTexts.6.png
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/Text/ConcatenatedText.swift
  Sources/Orbit/Support/Text/TextRepresentable+Concatenation.swift
  Sources/Orbit/Support/Text/TextRepresentable.swift
  Tests/SnapshotTests/Support Components/TextConcatenationTests.swift
Labels: enhancement

#656 Add inputFieldReturnAction to InputField
  Sources/Orbit/Orbit.docc/Components/Extensions/InputField.md
  Sources/Orbit/Support/Environment Keys/IconColorKey.swift
  Sources/Orbit/Support/Environment Keys/IconSizeKey.swift
  Sources/Orbit/Support/Environment Keys/IdealSizeKey.swift
  Sources/Orbit/Support/Environment Keys/Identifier.swift
  Sources/Orbit/Support/Environment Keys/InputFieldBeginEditingActionKey.swift
  Sources/Orbit/Support/Environment Keys/InputFieldEndEditingActionKey.swift
  Sources/Orbit/Support/Environment Keys/InputFieldFocusKey.swift
  Sources/Orbit/Support/Environment Keys/InputFieldReturnActionKey.swift
  Sources/Orbit/Support/Environment Keys/InputFieldShouldChangeCharactersActionKey.swift
  Sources/Orbit/Support/Environment Keys/InputFieldShouldReturnActionKey.swift
  Sources/Orbit/Support/Environment Keys/IsElevationEnabledKey.swift
  Sources/Orbit/Support/Environment Keys/IsExpandedKey.swift
  Sources/Orbit/Support/Environment Keys/IsFadeInEnabledKey.swift
  Sources/Orbit/Support/Environment Keys/IsInsideTileGroupKey.swift
  Sources/Orbit/Support/Environment Keys/IsTileSeparatorVisibleKey.swift
  Sources/Orbit/Support/Environment Keys/ScreenLayoutPaddingKey.swift
  Sources/Orbit/Support/Environment Keys/StatusKey.swift
  Sources/Orbit/Support/TextFields/TextField.swift
Labels: enhancement

#662 Improve `InputField` focus modifier
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Support/Environment Keys/InputFieldReturnActionKey.swift
  Sources/Orbit/Support/TextFields/TextField.swift
  Sources/Orbit/Support/TextFields/TextFieldCoordinator.swift
Labels: enhancement

#666 Refactor Dialog button builder
  Sources/Orbit/Components/Dialog.swift
Labels: maintenance

#668 Update accessibility of InputContent labels
  Sources/Orbit/Support/Forms/FieldLabel.swift
  Sources/Orbit/Support/Forms/FieldWrapper.swift
  Sources/Orbit/Support/Forms/InputContent.swift
Labels: maintenance, accessibility
