Repository kiwicom/orbit-swiftui, pull requests merged in 2023-06, with the labels that each got.

#586 Workaround for `IDPreference` crash
  Sources/Orbit/Support/Environment Keys/Identifier.swift
Labels: bug

#591 Added `Coupon` component
  Snapshots/iPad/CouponTests/testCoupons.1.png
  Snapshots/iPhone/CouponTests/testCoupons.1.png
  Sources/Orbit/Components/Coupon.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCoupon.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
  Sources/OrbitStorybook/Storybook+Items.swift
  Tests/SnapshotTests/Components/CouponTests.swift
  component-status.yaml
Labels: feature

#571 Configurable haptics
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/TextLink.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Components/BarButton.swift
  Sources/Orbit/Support/Components/NavigationButton.swift
  Sources/Orbit/Support/Environment Keys/HapticsEnabledKey.swift
Labels: accessibility

#607 Move behavior/presentation of `Button` to `OrbitButtonStyle`
  Snapshots/iPad/ButtonTests/testButtons.1.png
  Snapshots/iPad/ButtonTests/testButtons.2.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/ButtonTests/testButtons.1.png
  Snapshots/iPhone/ButtonTests/testButtons.2.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/Layout/IsEmpty.swift
Labels: enhancement

#603 Add inline label support to `Select`
  Snapshots/iPad/SelectTests/testSelects.1.png
  Snapshots/iPhone/SelectTests/testSelects.1.png
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Orbit.docc/Components/Extensions/InputField.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Forms/FieldLabel.swift
  Sources/Orbit/Support/Forms/FieldMessage.swift
  Sources/Orbit/Support/Forms/FieldWrapper.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Forms/InputContentButtonStyle.swift
  Sources/Orbit/Support/Forms/InputLabelStyle.swift
  Sources/Orbit/Support/Forms/InputStyle.swift
  Sources/Orbit/Support/Layout/TextStrut.swift
  Sources/OrbitStorybook/Detail/Items/StorybookInputField.swift
Labels: enhancement

#610 Update `ButtonLink` design
  Snapshots/iPad/AlertTests/testAlerts.1.png
  Snapshots/iPad/ButtonLinkTests/testButtonLinks.1.png
  Snapshots/iPad/ButtonLinkTests/testButtonLinks.2.png
  Snapshots/iPad/ButtonTests/testButtons.1.png
  Snapshots/iPad/ButtonTests/testButtons.2.png
  Snapshots/iPad/DialogTests/testDialog.1.png
  Snapshots/iPad/EmptyStateTests/testEmptyStates.1.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPad/SocialButtonTests/testSocialButtons.1.png
  Snapshots/iPhone/AlertTests/testAlerts.1.png
  Snapshots/iPhone/ButtonLinkTests/testButtonLinks.1.png
  Snapshots/iPhone/ButtonLinkTests/testButtonLinks.2.png
  Snapshots/iPhone/ButtonTests/testButtons.1.png
  Snapshots/iPhone/ButtonTests/testButtons.2.png
  Snapshots/iPhone/DialogTests/testDialog.1.png
  Snapshots/iPhone/EmptyStateTests/testEmptyStates.1.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/SocialButtonTests/testSocialButtons.1.png
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Skeleton.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Orbit.docc/Components/Extensions/ButtonLink.md
  Sources/Orbit/Support/Components/OrbitCustomButtonContent.swift
  Sources/Orbit/Support/Environment Keys/ButtonSizeKey.swift
  Sources/Orbit/Support/Layout/HorizontalScrollReader.swift
  Sources/Orbit/Support/Status.swift
  Sources/OrbitStorybook/Detail/Items/StorybookButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookButtonLink.swift
  Sources/OrbitStorybook/Detail/Items/StorybookHorizontalScroll.swift
Labels: enhancement

#612 `Alert` updates
  Plugins/CheckDocumentation/main.swift
  Snapshots/iPad/AlertInlineTests/testAlerts.1.png
  Snapshots/iPad/AlertTests/testAlerts.1.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/AlertInlineTests/testAlerts.1.png
  Snapshots/iPhone/AlertTests/testAlerts.1.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Components/AlertInline.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Orbit.docc/Components/Components.md
  Sources/Orbit/Orbit.docc/Components/Extensions/Alert.md
  Sources/Orbit/Orbit.docc/Components/Extensions/AlertInline.md
  Sources/Orbit/Support/Alert/AlertContent.swift
  Sources/Orbit/Support/Components/OrbitCustomButtonContent.swift
  Sources/Orbit/Support/ConditionalContent.swift
  Sources/Orbit/Support/Environment Keys/SuppressButtonStyleKey.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
  Sources/Orbit/Support/Status.swift
  Sources/OrbitStorybook/Detail/Items/StorybookAlert.swift
  Sources/OrbitStorybook/TutorialScreen.swift
  Tests/SnapshotTests/Components/AlertInlineTests.swift
Labels: enhancement
