Repository kiwicom/orbit-swiftui, pull requests merged in 2023-07, with the labels that each got.

#619 Add support for multiple options in SegmentedSwitch
  Snapshots/iPad/SegmentedSwitchTests/testSegmentedSwitch.2.png
  Snapshots/iPhone/SegmentedSwitchTests/testSegmentedSwitch.2.png
  Sources/Orbit/Components/SegmentedSwitch.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSegmentedSwitch.swift
Labels: enhancement

#620 Fix nil or false `idealSize` behaviour for some components.
  Snapshots/iPad/CardTests/testCards.1.png
  Snapshots/iPhone/CardTests/testCards.1.png
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Support/Components/OrbitCustomButtonContent.swift
  Sources/Orbit/Support/Environment Keys/ButtonSizeKey.swift
  Sources/Orbit/Support/Forms/InputContent.swift
Labels: bug

#624 Allow single `Alert` button to be styled as `secondary`
  Snapshots/iPad/AlertInlineTests/testAlerts.1.png
  Snapshots/iPad/AlertTests/testAlerts.1.png
  Snapshots/iPad/ButtonTests/testButtons.1.png
  Snapshots/iPad/ButtonTests/testButtons.2.png
  Snapshots/iPad/DialogTests/testDialog.1.png
  Snapshots/iPad/EmptyStateTests/testEmptyStates.1.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPad/SocialButtonTests/testSocialButtons.1.png
  Snapshots/iPhone/AlertInlineTests/testAlerts.1.png
  Snapshots/iPhone/AlertTests/testAlerts.1.png
  Snapshots/iPhone/ButtonTests/testButtons.1.png
  Snapshots/iPhone/ButtonTests/testButtons.2.png
  Snapshots/iPhone/DialogTests/testDialog.1.png
  Snapshots/iPhone/EmptyStateTests/testEmptyStates.1.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/SocialButtonTests/testSocialButtons.1.png
  Sources/Orbit/Components/Alert.swift
  Sources/Orbit/Orbit.docc/Components/Extensions/Button.md
  Sources/Orbit/Support/Alert/AlertContent.swift
  Sources/Orbit/Support/Components/OrbitCustomButtonContent.swift
  Sources/Orbit/Support/Environment Keys/ButtonPriorityKey.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
Labels: enhancement

#626 Padding and sizing of buttons is incorrect
  Snapshots/iPad/ButtonTests/testButtons.1.png
  Snapshots/iPad/ButtonTests/testButtons.2.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/ButtonTests/testButtons.1.png
  Snapshots/iPhone/ButtonTests/testButtons.2.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Sources/Orbit/Components/AlertInline.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Dialog.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Components/IconButton.swift
  Sources/Orbit/Support/Components/OrbitCustomButtonContent.swift
  Sources/Orbit/Support/Environment Keys/ButtonSizeKey.swift
Labels: bug

#629 Fix `ListChoice` and `Tile` separator
  Snapshots/iPad/HorizontalScrollTests/testHorizontalScrolls.1.png
  Snapshots/iPad/ListChoiceTests/testListChoices.1.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPad/TileGroupTests/testTileGroups.1.png
  Snapshots/iPhone/HorizontalScrollTests/testHorizontalScrolls.1.png
  Snapshots/iPhone/ListChoiceTests/testListChoices.1.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/TileGroupTests/testTileGroups.1.png
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
Labels: maintenance

#633 Improve `EmptyView` detection
  Sources/Orbit/Components/Badge.swift
  Sources/Orbit/Components/BadgeList.swift
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Components/Timeline.swift
  Sources/Orbit/Support/Forms/InputContent.swift
  Sources/Orbit/Support/Layout/IsEmpty.swift
  Sources/Orbit/Support/Layout/PotentiallyEmptyView.swift
Labels: enhancement
