Repository kiwicom/orbit-swiftui, pull requests merged in 2023-02, with the labels that each got.

#468 Make illustrations and images `RawRepresentable`
  Sources/Orbit/Foundation/Illustrations/Illustrations.swift
  Sources/Orbit/Support/Resources/AssetNameProviding.swift
  Sources/Orbit/Support/Resources/Images.swift
Labels: enhancement

#469 Expose `Orbit` bundle as `.orbit`
  Automation/update_colors.py
  Sources/Orbit/Components/CountryFlag.swift
  Sources/Orbit/Components/Illustration.swift
  Sources/Orbit/Foundation/Colors/Colors.swift
  Sources/Orbit/Foundation/Colors/Tokens.swift
  Sources/Orbit/Foundation/Colors/UIColor+Extensions.swift
  Sources/Orbit/Foundation/Typography/Font.swift
  Sources/Orbit/Support/Resources/Bundle.swift
  Sources/Orbit/Support/Resources/Images.swift
Labels: maintenance

#465 Use `Binding`s for control selection values
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Collapse.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Support/BindingSource.swift
  Sources/Orbit/Support/Components/TagGroup.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCheckbox.swift
  Sources/OrbitStorybook/Detail/Items/StorybookRadio.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTag.swift
Labels: enhancement

#470 Replace some initializer overloads by using default parameter type inference
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Support/Components/TimelineItem.swift
  Sources/Orbit/Support/Forms/FieldWrapper.swift
Labels: maintenance

#474 `Stepper` component
  Snapshots/iPad/StepperTests/testSteppers.1.png
  Snapshots/iPhone/StepperTests/testSteppers.1.png
  Sources/Orbit/Components/Stepper.swift
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/StepperButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookStepper.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
  Sources/OrbitStorybook/Storybook+Items.swift
  Tests/SnapshotTests/Components/StepperTests.swift
  component-status.yaml
Labels: feature

#463 `Stepper` component
  Sources/Orbit/Components/Stepper.swift
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Components/StepperButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookStepper.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
  Sources/OrbitStorybook/Storybook+Items.swift
  Tests/SnapshotTests/Components/StepperTests.swift
  component-status.yaml
Labels: feature

#476 Support automatic mirroring for certain `Icon` symbols
  Sources/Orbit/Components/Icon.swift
Labels: enhancement
