Repository kiwicom/orbit-swiftui, pull requests merged in 2023-05, with the labels that each got.

#457 `Slider` component
  Snapshots/iPad/SliderTests/testSlider.1.png
  Snapshots/iPhone/SliderTests/testSlider.1.png
  Sources/Orbit/Components/Slider.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/Components/SliderThumb.swift
  Sources/Orbit/Support/Previews/PreviewFormatting.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSlider.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
  Sources/OrbitStorybook/Storybook+Items.swift
  Tests/SnapshotTests/Components/SliderTests.swift
  component-status.yaml
Labels: feature

#563 Duplicate fonts registration fix
  Sources/Orbit/Foundation/Typography/Font.swift
Labels: maintenance

#566 Add isSelected trait to `Tag`
  Sources/Orbit/Components/Tag.swift
Labels: accessibility

#570 Update release drafter configuration
  .github/release-drafter.yml
Labels: automation

#484 Update `SegmentedSwitch` to take a `Hashable` binding
  Snapshots/iPad/SegmentedSwitchTests/testSegmentedSwitch.1.png
  Snapshots/iPad/SegmentedSwitchTests/testSegmentedSwitch.2.png
  Snapshots/iPhone/SegmentedSwitchTests/testSegmentedSwitch.1.png
  Snapshots/iPhone/SegmentedSwitchTests/testSegmentedSwitch.2.png
  Sources/Orbit/Components/SegmentedSwitch.swift
  Sources/Orbit/Support/EnvironmentReader.swift
  Sources/Orbit/Support/PreferenceReader.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSegmentedSwitch.swift
Labels: enhancement

#581 Add `textFontWeight` modifier
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/Environment Keys/TextFontWeightKey.swift
Labels: enhancement

#577 `Tabs` updates
  Snapshots/iPad/TabsTests/testTabs.1.png
  Snapshots/iPad/TabsTests/testTabs.2.png
  Snapshots/iPhone/TabsTests/testTabs.1.png
  Snapshots/iPhone/TabsTests/testTabs.2.png
  Sources/Orbit/Components/SegmentedSwitch.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Orbit.docc/Components/Extensions/Tabs.md
  Sources/Orbit/Support/Components/BackgroundHighlightButtonStyle.swift
  Sources/Orbit/Support/Components/Tab.swift
  Sources/Orbit/Support/Components/TabStyle.swift
  Sources/Orbit/Support/Environment Keys/ActiveTabStyleKey.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTabs.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
Labels: enhancement
