Repository kiwicom/orbit-swiftui, pull requests merged in 2023-01, with the labels that each got.

#400 Replace CircularPro with Circular20 font
  Package.swift
  Sources/Orbit/Foundation/Typography/Font.swift
  Sources/Orbit/Orbit.docc/GettingStarted.md
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s07.swift
  Sources/Orbit/Orbit.docc/Resources/Tutorials/01-01-hello_orbit-s08.swift
  Sources/Orbit/Orbit.docc/Tutorials/01-01-hello_orbit.tutorial
Labels: maintenance

#412 Remove `display` and `displaySubtitle` Heading styles
  Snapshots/iPad/HeadingTests/testHeadings.1.png
  Snapshots/iPad/TextConcatenationTests/testTextConcatenation.1.png
  Snapshots/iPhone/HeadingTests/testHeadings.1.png
  Snapshots/iPhone/TextConcatenationTests/testTextConcatenation.1.png
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Support/TextConcatenation/TextRepresentable+Concatenation.swift
  Sources/OrbitStorybook/Foundation/StorybookTypography.swift
Labels: maintenance

#415 Make readableMaxWidth overridable
  Sources/Orbit/Support/Layout/Layout.swift
Labels: enhancement

#418 Add inline `Alert`
  Snapshots/iPad/AlertTests/testAlerts.1.png
  Snapshots/iPhone/AlertTests/testAlerts.1.png
  Sources/Orbit/Components/Alert.swift
  Sources/OrbitStorybook/Detail/Items/StorybookAlert.swift
  Sources/OrbitStorybook/Detail/StorybookDetail.swift
Labels: feature

#421 Fix ChoiceTile content padding
  Snapshots/iPad/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iPad/ChoiceTileTests/testChoiceTiles.2.png
  Snapshots/iPad/ChoiceTileTests/testChoiceTiles.3.png
  Snapshots/iPhone/ChoiceTileTests/testChoiceTiles.1.png
  Snapshots/iPhone/ChoiceTileTests/testChoiceTiles.2.png
  Snapshots/iPhone/ChoiceTileTests/testChoiceTiles.3.png
  Snapshots/iPhone/ListChoiceTests/testListChoices.1.png
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/ListChoice.swift
Labels: bug

#434 Remove parameter label from state wrappers
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Collapse.swift
  Sources/Orbit/Components/InputField.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/SegmentedSwitch.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/Switch.swift
  Sources/Orbit/Components/Tabs.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/TextLink.swift
  Sources/Orbit/Support/Components/PasswordStrengthIndicator.swift
  Sources/Orbit/Support/Components/Progress.swift
  Sources/Orbit/Support/Components/TagGroup.swift
  Sources/Orbit/Support/Forms/FieldWrapper.swift
  Sources/Orbit/Support/Layout/ContentHeightReader.swift
  Sources/Orbit/Support/Previews/StateObjectWrapper.swift
  Sources/Orbit/Support/Previews/StateWrapper.swift
  Sources/OrbitStorybook/Detail/Items/StorybookAlert.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCheckbox.swift
  Sources/OrbitStorybook/Detail/Items/StorybookChoiceTile.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCollapse.swift
  Sources/OrbitStorybook/Detail/Items/StorybookInputField.swift
  Sources/OrbitStorybook/Detail/Items/StorybookRadio.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSegmentedSwitch.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSwitch.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTabs.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTag.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTextLink.swift
Labels: maintenance

#432 Remove unused `UIFont` enum
  Sources/Orbit/Foundation/Typography/UIFont.swift
  Sources/Orbit/Support/TextLinks/TagAttributedStringBuilder.swift
Labels: maintenance

#431 Update API for multiple viewbuilder content
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/ListChoice.swift
Labels: maintenance

#438 Update ListChoice init
  Snapshots/iPhone/ListChoiceTests/testListChoices.1.png
  Sources/Orbit/Components/ListChoice.swift
  Sources/OrbitStorybook/Detail/Items/StorybookListChoice.swift
Labels: bug

#440 Empty `Button` shrinks due to missing `TextStrut`
  Snapshots/iPad/ButtonTests/testButtons.2.png
  Snapshots/iPhone/ButtonTests/testButtons.2.png
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/SegmentedSwitch.swift
Labels: bug

#443 Update inline Alert layout to match design
  Snapshots/iPad/AlertTests/testAlerts.1.png
  Snapshots/iPhone/AlertTests/testAlerts.1.png
  Sources/Orbit/Components/Alert.swift
Labels: maintenance

#452 Update TextLink accessibility
  Sources/Orbit/Components/Text.swift
Labels: accessibility

#454 Fix `TextLink` kerning issue when kerning is exactly zero
  Snapshots/iPad/AlertTests/testAlerts.1.png
  Snapshots/iPad/BadgeListTests/testBadgeLists.1.png
  Snapshots/iPad/CheckboxTests/testCheckboxes.1.png
  Snapshots/iPad/HeadingTests/testHeadings.3.png
  Snapshots/iPad/RadioTests/testRadios.1.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPad/TextLinkTests/testTextLinks.1.png
  Snapshots/iPad/TextTests/testTexts.1.png
  Snapshots/iPad/TextTests/testTexts.2.png
  Snapshots/iPad/TextTests/testTexts.3.png
  Snapshots/iPhone/AlertTests/testAlerts.1.png
  Snapshots/iPhone/BadgeListTests/testBadgeLists.1.png
  Snapshots/iPhone/CheckboxTests/testCheckboxes.1.png
  Snapshots/iPhone/HeadingTests/testHeadings.3.png
  Snapshots/iPhone/RadioTests/testRadios.1.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/TextLinkTests/testTextLinks.1.png
  Snapshots/iPhone/TextTests/testTexts.1.png
  Snapshots/iPhone/TextTests/testTexts.2.png
  Snapshots/iPhone/TextTests/testTexts.3.png
  Sources/Orbit/Support/TextLinks/TagAttributedStringBuilder.swift
  Sources/Orbit/Support/TextLinks/TextLinkView.swift
Labels: bug

#455 453 kerning of text and textlink is not in sync
  Snapshots/iPad/TextTests/testTexts.1.png
  Snapshots/iPhone/TextTests/testTexts.1.png
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/TextLink.swift
  Sources/Orbit/Support/TextLinks/TagAttributedStringBuilder.swift
  Sources/Orbit/Support/TextLinks/Text+AttributedString.swift
Labels: bug

#449 Remove default values for component actions
  Sources/Orbit/Components/Button.swift
  Sources/Orbit/Components/ButtonLink.swift
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/Checkbox.swift
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/EmptyState.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Radio.swift
  Sources/Orbit/Components/Select.swift
  Sources/Orbit/Components/SocialButton.swift
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Components/TileGroup.swift
  Sources/Orbit/Components/Toast.swift
  Sources/Orbit/Support/Components/BarButton.swift
  Sources/Orbit/Support/Components/NavigationButton.swift
  Sources/Orbit/Support/Components/TileBorder.swift
  Sources/Orbit/Support/Components/TimelineItem.swift
  Sources/Orbit/Support/Layout/IgnoreScreenLayoutHorizontalPaddingModifier.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
  Sources/Orbit/Support/Layout/TextStrut.swift
  Sources/Orbit/Support/Previews/Measurements.swift
  Sources/OrbitStorybook/Detail/Items/StorybookButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookButtonLink.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCard.swift
  Sources/OrbitStorybook/Detail/Items/StorybookEmptyState.swift
  Sources/OrbitStorybook/Detail/Items/StorybookListChoice.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSelect.swift
  Sources/OrbitStorybook/Detail/Items/StorybookSocialButton.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTag.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTile.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTileGroup.swift
  Sources/OrbitStorybook/TutorialScreen.swift
Labels: maintenance
