Repository kiwicom/orbit-swiftui, pull requests merged in 2024-03, with the labels that each got.

#771 Fix DocC warnings
  Sources/Orbit/Components/ChoiceTile.swift
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Components/Tile.swift
  Sources/Orbit/Orbit.docc/Components/Components.md
  Sources/Orbit/Orbit.docc/FileStructureAndNaming.md
  Sources/Orbit/Orbit.docc/Foundation/Elevation.md
  Sources/Orbit/Orbit.docc/Uncategorized.md
  Sources/Orbit/Support/Environment Keys/InputFieldShouldReturnActionKey.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
Labels: documentation

#772 Update `Card` to use environment value to drive the content layout
  Snapshots/iPad/CardTests/testCards.1.png
  Snapshots/iPad/IllustrationTests/testIllustrations.1.png
  Snapshots/iPhone/CardTests/testCards.1.png
  Snapshots/iPhone/IllustrationTests/testIllustrations.1.png
  Sources/Orbit/Components/Card.swift
  Sources/Orbit/Components/ListChoice.swift
  Sources/Orbit/Orbit.docc/Components/Extensions/Card.md
  Sources/Orbit/Support/Environment Keys/CardLayoutKey.swift
  Sources/Orbit/Support/Layout/IgnoreScreenLayoutHorizontalPaddingModifier.swift
  Sources/Orbit/Support/Layout/ScreenLayoutModifier.swift
  Sources/OrbitStorybook/Detail/Items/StorybookCard.swift
  Sources/OrbitStorybook/Detail/Items/StorybookListChoice.swift
  Sources/OrbitStorybook/Foundation/StorybookColors.swift
Labels: enhancement

#775 Update `Card` description color and its customization
  Snapshots/iPad/CardTests/testCards.1.png
  Snapshots/iPad/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Snapshots/iPhone/CardTests/testCards.1.png
  Snapshots/iPhone/ScreenLayoutModifierTests/testScreenLayoutModifier.1.png
  Sources/Orbit/Components/Card.swift
Labels: enhancement

#778 Add `Sendable` conformance to `AccessibilityID`
  Sources/Orbit/Support/Accessibility/AccessibilityID.swift
Labels: accessibility

#781 Add localization support to Text component
  Sources/Orbit/Components/Heading.swift
  Sources/Orbit/Components/Icon.swift
  Sources/Orbit/Components/Text.swift
  Sources/Orbit/Support/Environment Keys/LocalizationBundle.swift
  Sources/Orbit/Support/Text/ConcatenatedText.swift
  Sources/Orbit/Support/Text/LocalizedStringKey.swift
  Sources/Orbit/Support/Text/TextRepresentable.swift
  Sources/OrbitIllustrations/Components/Illustration.swift
  Sources/OrbitStorybook/Storybook.swift
Labels: feature

#785 Replace `TagStyle` with `removeAction`
  Sources/Orbit/Components/Tag.swift
  Sources/Orbit/Support/ButtonStyles/TagButtonStyle.swift
  Sources/OrbitStorybook/Detail/Items/StorybookTag.swift
Labels: feature

#788 Fix `redacted` for `UIViewRepresentable` views
  Sources/Orbit/Components/TextLink.swift
  Sources/Orbit/Support/TextFields/TextField.swift
  Sources/Orbit/Support/TextFields/TextView.swift
Labels: bug
